// Code generated by MockGen. DO NOT EDIT.
// Source: ./types.go

// Package daomocks is a generated GoMock package.
package daomocks

import (
	context "context"
	reflect "reflect"
	time "time"

	task "github.com/ecodeclub/ecron/internal/task"
	gomock "go.uber.org/mock/gomock"
)

// MockTaskCfgRepository is a mock of TaskCfgRepository interface.
type MockTaskCfgRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTaskCfgRepositoryMockRecorder
}

// MockTaskCfgRepositoryMockRecorder is the mock recorder for MockTaskCfgRepository.
type MockTaskCfgRepositoryMockRecorder struct {
	mock *MockTaskCfgRepository
}

// NewMockTaskCfgRepository creates a new mock instance.
func NewMockTaskCfgRepository(ctrl *gomock.Controller) *MockTaskCfgRepository {
	mock := &MockTaskCfgRepository{ctrl: ctrl}
	mock.recorder = &MockTaskCfgRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskCfgRepository) EXPECT() *MockTaskCfgRepositoryMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockTaskCfgRepository) Add(ctx context.Context, t task.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, t)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockTaskCfgRepositoryMockRecorder) Add(ctx, t interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockTaskCfgRepository)(nil).Add), ctx, t)
}

// Stop mocks base method.
func (m *MockTaskCfgRepository) Stop(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockTaskCfgRepositoryMockRecorder) Stop(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockTaskCfgRepository)(nil).Stop), ctx, id)
}

// UpdateNextTime mocks base method.
func (m *MockTaskCfgRepository) UpdateNextTime(ctx context.Context, id int64, next time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNextTime", ctx, id, next)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateNextTime indicates an expected call of UpdateNextTime.
func (mr *MockTaskCfgRepositoryMockRecorder) UpdateNextTime(ctx, id, next interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNextTime", reflect.TypeOf((*MockTaskCfgRepository)(nil).UpdateNextTime), ctx, id, next)
}

// MockExecutionDAO is a mock of ExecutionDAO interface.
type MockExecutionDAO struct {
	ctrl     *gomock.Controller
	recorder *MockExecutionDAOMockRecorder
}

// MockExecutionDAOMockRecorder is the mock recorder for MockExecutionDAO.
type MockExecutionDAOMockRecorder struct {
	mock *MockExecutionDAO
}

// NewMockExecutionDAO creates a new mock instance.
func NewMockExecutionDAO(ctrl *gomock.Controller) *MockExecutionDAO {
	mock := &MockExecutionDAO{ctrl: ctrl}
	mock.recorder = &MockExecutionDAOMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExecutionDAO) EXPECT() *MockExecutionDAOMockRecorder {
	return m.recorder
}

// Upsert mocks base method.
func (m *MockExecutionDAO) Upsert(ctx context.Context, id int64, status task.ExecStatus, progress uint8) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, id, status, progress)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upsert indicates an expected call of Upsert.
func (mr *MockExecutionDAOMockRecorder) Upsert(ctx, id, status, progress interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockExecutionDAO)(nil).Upsert), ctx, id, status, progress)
}
